<?php

namespace FosterMade\Genly\Command;

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Common extends AbstractCommand
{
    protected function configure()
    {
        parent::configure();

        $this->setName('common');
        $this->ignoreValidationErrors();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $input->setOption('common', true);

        parent::execute($input, $output); // TODO: Change the autogenerated stub

        /** @var AbstractCommand $command */
        $command = $this->getApplication()->find($_SERVER['argv'][2]);

        if (false === $command->supportsCommon()) {
            throw new \Exception(sprintf("The '%s' command cannot be run for common containers.", $_SERVER['argv'][2]));
        }

        $in = new ArgvInput(array_slice($_SERVER['argv'], 1));

        return $command->run($in, $output);
    }
}
